---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "libvirt-exporter.fullname" . }}
  labels:
{{- include "libvirt-exporter.labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.libvirtExporterPort }}
    targetPort: metrics
  selector:
{{- include "libvirt-exporter.labels" . | indent 4 }}
