apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "libvirt-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "libvirt-exporter.labels" . | indent 4 }}
spec:
  endpoints:
  - interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    port: metrics
  jobLabel: jobLabel
  namespaceSelector:
    any: true
  selector:
    matchLabels:
{{ include "libvirt-exporter.labels" . | indent 6 }}
